### ISSUE TITLE
L2-norm of 2048-embeddimgs before fc in linear evaluation stage?

### ISSUE THREAD

**Issue by haohang96** [mdiephuis/SimCLR#3]
In your implementation, It seems that the 2048-dim embeddings are prepocessed with l2-norm and then fed into fc in linear evaluation stage. Is it the official way of simCLR? Thanks!

**Comment by mdiephuis** [comment]
The embeddings are passed on without normalization to the head (line 311, models.py) but both _z_ and _h_ are normalized prior to the loss and as final feature. The latter the paper doesn't do.
