### ISSUE TITLE
Code Errors and Low Classifier Accuracy

### ISSUE THREAD

**Issue by CristianManta** [mdiephuis/SimCLR#4]
![Screenshot from 2020-08-06 11-45-52](https://user-images.githubusercontent.com/60302312/89553897-1e56bf80-d7dc-11ea-9b9f-88bed7809346.png)
Hello,

I appreciate the effort you put into this. I came across your repo in order to get a good encoder model for future experiments. 

I ran your pre-training code with the following arguments:
```python

CUDA_VISIBLE_DEVICES=0,1,2,3 python train_features.py \
    --batch-size=64 \
    --accumulation-steps=4 \
    --tau=0.5 \
    --feature-size=128 \
    --dataset-name=CIFAR10C \
    --data-dir=/actual/absolute/path \
    --multi-gpu
```

The only change that I brought to the code was at line 155: the `device_ids` was changed to `[0, 1, 2, 3]`.

And after that, I ran the classifier training code with 
```python

CUDA_VISIBLE_DEVICES=0,1,2,3 python train_classifier.py \
    --load-model=models/Aug-06-2020_0331_SimCLR_149_0.0119.pt \
    --dataset-name=CIFAR10 \
    --data-dir=/same/path/as/before
```

The first problem is that the code throws this error: 
```
Traceback (most recent call last):                                                                                                                                                            
  File "train_classifier.py", line 163, in <module>                                                                                                                                           
    feature_model.load_state_dict(checkpoint['model'])                                                                                                                                        
  File "/path/to/anaconda3/envs/simclr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 830, in load_state_dict                                                 
    self.__class__.__name__, "\n\t".join(error_msgs)))                                                                                                                                        
RuntimeError: Error(s) in loading state_dict for ResNet_CIFAR:                                                                                                                                
        Missing key(s) in state_dict:
```
And then a long list of keys follow (see attached picture if you want to see how it looks like).

I saw that a quick way to fix it is to set `feature_model.load_state_dict(checkpoint['model'], strict=False)` at line 163 in `train_classifier.py`. However, I'm told that we should always push the model to cuda after loading the weights, not before. You seem to do the opposite. Maybe this is contributing to the problem and `strict=False` is just a cheap patch that hides the problem because...

When I re-ran the classifier script, the validation accuracy that I got was 44% after 100 epochs and 37.5% after 200 epochs, so the classifier doesn't seem to learn.

You claim to have an accuracy of at least 85% and I'd like to reproduce that. None of my attempts to fix your code worked. Do you have an idea of what might be causing this issue and how to fix it? Thank you very much.

Cristian

**Comment by mdiephuis** [comment]
Cristian,

Thanks a lot for raising this issue. You are right. In short, there seem to be two things broken:
- LARS (at least on my machine)
- The multi-gpu option when training the classifier. 

We will go over the multi-gpu code at some point again, but for now, we pushed an update which removed these two options. We will also dig up some checkpoints to share. 

Good luck!

**Comment by CristianManta** [comment]
Thank you for your response!

Cristian
